### ISSUE TITLE
Index Route always displaying data when using middleware

### ISSUE THREAD

**Issue by compilekaiten** [DeveloperMarius/simple-php-router#11]
I'm attempting to create a dashboard for a project, and I wanted to utilize this router.

I've created a Auth middleware to check if a user it logged in, but I'm facing an issue where my index route `/` is displayed after my login page. Here's a very basic image of the output I'm getting: https://prnt.sc/bpG4QedTXY7v
You can see that my login page echoes `login page` followed by `index route` and back to `login page`. It should only echo `login page`.

Edit: This isn't only happening on the `/` route. If I add another route like `/home` to this router group and visit it, it'll display my Login page, and then my Index/Home page underneath it. 

My routes.php is as follows: 
```php
// Auth Guarded Routes
SimpleRouter::group(['middleware' => \middlewares\authGuard\authGuard::class], function () {
    // Index
    SimpleRouter::get('/', function () {
        echo "index route";
        include_once('../app/views/home/home.php');
    });
	
	// Login
    SimpleRouter::get('/login', function () {
		echo "login page";
        include_once('../app/views/login/login.php');
    });
});
```

My authGuard class is as follows:
```php
namespace middlewares\authGuard;

include_once('../app/config.php');

use Pecee\Http\Middleware\IMiddleware;
use Pecee\Http\Request;
use vault\authGuard\authController;

class authGuard implements IMiddleware {

    public function handle(Request $request): void {

		// Init Auth Controller
        $authController = new authController();
		// Get True or False back from Auth Controller
        $request->user = $authController->checkLogin();

        // If authentication failed, redirect request to user-login page.
        if ($request->user == null || false) {
            request()->setRewriteUrl('/login');
        }
    }
}
```

Am I doing something wrong here?

**Comment by xJuvi** [comment]
I think there are two errors.

First your authGuard Middleware is global for both routes. So if you visit the /login path, the auth middleware will rewrite the url again.

The second mistake is that you use request()->setRewriteUrl() - i think you should rewrite the route with request()->setRewriteRoute(ILoadableRoute $route). Else you can use request()->setRewriteCallback(Closure|string $callback). Booth methods works better with controllers.

btw inside the middleware you can use $request instead of the helper function request().

Here is an example, but it's old and based on the original framework. Some methods are changed since we work with this fork:
https://github.com/skipperbent/simple-router-demo

**Comment by compilekaiten** [comment]
> 

Hi, thanks for the answer! I think I'm understanding this correctly, but I'm still a bit confused on why my `/home` route is still rendering when I'm not authenticated. My understanding was that the Middleware would stop any other requests/calls to render anything and just execute `setRewriteCallback`. Is there a way to halt execution of anything else after 

The `/home` route is in my middleware group, the `authGuard` class checks the auth status (session key), and returns True or False, and sets the rewrite using `setRewriteCallback` to my viewDispatcher class (just requires the specific file) for `/login` or `/home`.

But when I'm not authenticated, and I go to the `/home` URL, my login page gets rendered, and underneath it, is the home page. 
Picture: https://prnt.sc/5zVY0IHr21qC

My Routes.php: 
```php
/* ========================================
? Auth Guarded Routes
======================================== */
SimpleRouter::group(['middleware' => authGuard::class], function () {
    SimpleRouter::get('/', function () {
        //"PLACEHOLDER... idk what to do with this..., if it's not here, everything is a 404";
    });

    // Home Page if Authenticated
    SimpleRouter::get('/home', [viewDispatcher::class, 'home']);
});

/* ========================================
? Unguarded Routes
======================================== */
// Render Login Page
SimpleRouter::get('/login', [viewDispatcher::class, 'login']);
// POST /login -> Submit Auth -> Redirect to home or back to login depending on return value
SimpleRouter::post('/login', [authController::class, 'doLogin']);
// Logout and Redirect to Login Page
SimpleRouter::get('/logout', [authController::class, 'logout']);
// Render Register Page
SimpleRouter::get('/register', [viewDispatcher::class, 'register']);
```
AuthGuard.php
```php
class authGuard implements IMiddleware {
    use RouterUtils;

    public function handle(Request $request): void {
        // Init Auth Controller
        $authController = new authController();

        // Auth Check returns TRUE or FALSE
        $request->auth = $authController->checkLogin();

        // If authentication failed, redirect request to Login Page
        if (!$request->auth) {
            // View Dispatcher that renders the LOGIN page if Auth is FALSE
            $request->setRewriteCallback('vault\controllers\viewDispatcher@login');
        } else {
            // View Dispatcher that renders the HOME page if Auth is TRUE
            $request->setRewriteCallback('vault\controllers\viewDispatcher@home');
        }
    }
}
```
ViewDispatcher.php
```php
class viewDispatcher {
    public function home() {
        try {
            require('../app/views/home/home.php');
        } catch (\Throwable $th) {
            //placeholder
            echo $th->getMessage();
        }
    }
}
```

**Comment by compilekaiten** [comment]
@xJuvi @DeveloperMarius Any ideas why I'm experiencing this issue? Am I doing something wrong? Have I not understood how the middlewares function?

Really want to use this Router, but not being able to properly guard routes is going to be a problem. 

Thanks

**Comment by DeveloperMarius** [comment]
Hello,

I have a view points:
1. Please provide a prefix to the group if you do not have a '/' route. I think this is your problem with the "/" route.
2. A middleware intercepts a request and does some checks before allowing the user to access a page. That results in you not having to redirect the user every time, if he is already logged in. When you do this, every request (logged in) is redirected to home and the other redirected to login (not logged in). Please take a look at my example / test in `tests/Pecee/SimpleRouter/CustomMiddlewareTest.php@testAuthMiddlewareWithEchoCallback`
3. For your viewDispatcher maybe take a look at an ExceptionHandler

I fixed an issue with using echo instead of return. Now, both methods to print content work as expected.

Thank you for reporting this issue and I will release a fix soon.

~ Marius
