### ISSUE TITLE
PHPStan - Call to an undefined method

### ISSUE THREAD

**Issue by xJuvi** [DeveloperMarius/simple-php-router#18]
Hi,
I have my code checked by PHPStan in a Github action. My routes are displayed as faulty:

```log
  36     Call to an undefined method Pecee\SimpleRouter\Route\IRoute::where().
```

And my line 36 includes this:

```php
Router::post('/{id}/get/', 'InternalApiController@loadLocation')->where([ 'id' => '[0-9]+' ])->name('api_getLocation');
```

Have I made a mistake in the implementation? The code works and I can call up the route. The error is displayed for all routes that contain a **where** or **name**.

**Comment by DeveloperMarius** [comment]
Hey,
thanks for reporting this issue.
`where` is just an alias for `setWhere`, thus it was not listed in the `IRoute` interface. I think that PHPStan only looked at the `IRoute` instead of the normal `Route` class for its methods, because somewhere there was only the `IRoute` type returned.
I added the `where` method to the interface and this should fix your issue.
Can you please install the dev-master version of this repo and check? 
If this fixes your problem, please let me know and I can release a new version with this fix.

~ Marius

**Comment by xJuvi** [comment]
Hi Marius,
it works. Thanks.
Additional i noticed, the same behavior is for the alias `name()` in the `ILoadableRoute` - this is missing there. Could you also add this?

Thank for your fast response.

**Comment by DeveloperMarius** [comment]
Hey,
I fixed that too now.

Thanks again for reporting.

~ Marius
